import { useEffect, useState } from 'react';
import { Download, FileText, Search } from 'lucide-react';
import { facturaService, type InvoiceSummary } from '../services/factura.service';
import { Card } from '../../../core/ui/Card';

export default function FacturasPage() {
  const [invoices, setInvoices] = useState<InvoiceSummary[]>([]);
  const [search, setSearch] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { facturaService.getInvoices().then(setInvoices).catch(caught => setError(caught instanceof Error ? caught.message : 'No fue posible cargar las facturas.')); }, []);
  const filtered = invoices.filter(invoice => `${invoice.number}`.toLowerCase().includes(search.toLowerCase()));
  return <main className="mx-auto w-full max-w-7xl px-6 py-6 pb-24 md:px-8 md:py-8"><header className="mb-8 flex items-center justify-between"><div><h1 className="text-2xl font-black text-ink">Gestión de facturas</h1><p className="mt-1 text-sm font-semibold text-ink-muted">Consulta y seguimiento de facturación</p></div><button type="button" className="hidden min-h-11 items-center gap-2 rounded-2xl border border-surface-border bg-white px-4 text-xs font-black text-ink-muted md:flex"><Download size={18} className="text-brand-blue" /> Exportar</button></header>{error && <p role="alert" className="mb-6 rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<div className="mb-6 flex items-center gap-3 rounded-2xl border border-surface-border bg-white px-4 py-3"><Search size={18} className="text-ink-light" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar por factura" className="w-full outline-none" aria-label="Buscar factura" /></div><Card padding="none" className="overflow-hidden"><div className="divide-y divide-surface-border md:hidden">{filtered.map(invoice => <div key={invoice.id} className="flex items-center justify-between p-5"><div><strong className="block text-sm text-ink">{invoice.number}</strong><span className="text-xs text-ink-muted">{invoice.date}</span></div><div className="text-right"><strong className="block text-sm text-ink">${invoice.total.toLocaleString()}</strong><span className="text-xs font-bold text-brand-blue">{invoice.status}</span></div></div>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full text-left"><thead className="bg-surface-soft text-[10px] font-black uppercase tracking-widest text-ink-muted"><tr><th className="p-4">Factura</th><th className="p-4">Fecha</th><th className="p-4">Estado</th><th className="p-4 text-right">Monto</th><th className="p-4" /></tr></thead><tbody className="divide-y divide-surface-border">{filtered.map(invoice => <tr key={invoice.id}><td className="p-4 font-bold text-ink">{invoice.number}</td><td className="p-4 text-sm text-ink-muted">{invoice.date}</td><td className="p-4 text-sm font-bold text-brand-blue">{invoice.status}</td><td className="p-4 text-right font-black text-ink">${invoice.total.toLocaleString()}</td><td className="p-4"><button type="button" className="min-h-11 min-w-11 text-ink-muted" aria-label={`Ver factura ${invoice.number}`}><FileText size={18} className="mx-auto" /></button></td></tr>)}</tbody></table></div>{!error && filtered.length === 0 && <p className="p-10 text-center text-sm font-semibold text-ink-muted">No hay facturas para mostrar.</p>}</Card></main>;
}
